name: Release

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install
        run: yarn install --immutable --immutable-cache

      - name: Build
        run: yarn build:ci

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test

      - name: Release
        id: release
        if: github.event_name == 'push'
        uses: GoogleCloudPlatform/release-please-action@v2
        with:
          command: manifest

      - name: Publish
        if: ${{ steps.release.outputs.releases_created }}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: ./tools/publish_paths.sh '${{ steps.release.outputs.paths_released }}'
